### ISSUE TITLE
dorion@5.0.1 - Unable to Open

### ISSUE THREAD

**Issue by PlatFlat** [Small-Ku/turbo-bucket#45]
Unable to open Dorion, current log shows:

`Panic occurred: PanicInfo { payload: Any { .. }, message: Some(Config does not exist!: Os { code: 5, kind: PermissionDenied, message: "Access is denied." }), location: Location { file: "src\\config.rs", line: 52, col: 35 }, can_unwind: true, force_no_backtrace: false }
`

Scoop Dorion directory:

![image](https://github.com/user-attachments/assets/3de20c15-123a-4011-b01f-59041e428826)

Antivirus/WinDef disabled, UAC off.

**Comment by Small-Ku** [comment]
Please try to remove the config.json folder in persist and install again after 1626bd6

**Comment by Small-Ku** [comment]
Should be fixed with https://github.com/Small-Ku/turbo-bucket/commit/9a60766e4bc0ba4d0d8ebd35c8904d8b25dc200c this time. Please remove the persist and try again.
